title: A-J Mäki
description: Test pages
# description: PhD, Data Engineer & Passionate Data Guy 
logo: /pics/headshot_circle_ajm.png
show_downloads: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme